--1
SELECT TOP 50 PERCENT * FROM BORROW

--2
SELECT TOP 10 PERCENT AMOUNT FROM DEPOSIT

--3
SELECT TOP 25 PERCENT CNAME FROM DEPOSIT WHERE AMOUNT > 5000

--4
SELECT TOP 10 PERCENT AMOUNT FROM BORROW

--5
SELECT DISTINCT CNAME, CITY FROM CUSTOMERS

--6
SELECT *, (AMOUNT + AMOUNT*0.1) AS 'EXTRA AMOUNT' FROM BORROW

--7
SELECT LOANNO FROM BORROW WHERE LOANNO % 2 = 1

SELECT LOANNO FROM BORROW WHERE LOANNO % 2 = 0
